### ISSUE TITLE
Feature request: 只在群聊环境下默认禁用指令

### ISSUE THREAD

**Issue by DGCK81LNN** [koishijs/koishi-plugin-switch#6]
由于我的 bot 成分复杂，需要默认禁用多数功能，随后在不同群聊中启用不同功能。然而这样做会导致多数功能都无法在私聊中使用；希望能够允许在私聊使用所有功能，而不影响 bot 在新加入的群聊中默认禁用多数功能。

**Comment by Hieuzest** [comment]
switch 指令本身并不能在私聊上下文中使用，因此使默认逻辑直接忽略私聊场景应当是合理的。
